import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
import {defineConfig, loadEnv} from 'vite';

export default defineConfig(({mode}) => {
  const env = loadEnv(mode, process.cwd(), '');
  const apiKey = process.env.GEMINI_API_KEY || env.GEMINI_API_KEY || process.env.API_KEY || env.API_KEY || process.env.GOOGLE_API_KEY || env.GOOGLE_API_KEY;

  if (apiKey) {
    try {
      const configPath = path.resolve(__dirname, 'src/config.ts');
      const configContent = `// Configuration file
// Auto-generated by vite.config.ts

export const CONFIG = {
  GEMINI_API_KEY: "${apiKey}", 
};
`;
      fs.writeFileSync(configPath, configContent);
      console.log("Injected API Key into src/config.ts");
    } catch (e) {
      console.error("Failed to inject API key:", e);
    }
  }

  return {
    plugins: [react(), tailwindcss()],
    define: {
      'process.env.GEMINI_API_KEY': JSON.stringify(apiKey),
      'process.env.API_KEY': JSON.stringify(apiKey),
    },
    envPrefix: ['VITE_', 'GEMINI_', 'API_'],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modifyâfile watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
    },
  };
});
