import React, { createContext, useState, useEffect, useContext } from 'react';

type Language = 'tr' | 'en' | 'de' | 'fr' | 'ru' | 'ja' | 'zh';

interface Translations {
  [key: string]: {
    [key in Language]: string;
  };
}

export const translations: Translations = {
  'nav.daily': { tr: 'Günlük Rapor', en: 'Daily Report', de: 'Tagesbericht', fr: 'Rapport Quotidien', ru: 'Ежедневный Отчет', ja: '日次レポート', zh: '每日报告' },
  'nav.about': { tr: 'Hakkında', en: 'About', de: 'Über', fr: 'À propos', ru: 'О нас', ja: 'について', zh: '关于' },
  'nav.map': { tr: 'Harita', en: 'Map', de: 'Karte', fr: 'Carte', ru: 'Карта', ja: '地図', zh: '地图' },
  'nav.live': { tr: 'Canlı Yayın', en: 'Live Stream', de: 'Live-Stream', fr: 'En direct', ru: 'Прямой эфир', ja: 'ライブ配信', zh: '直播' },
  
  'report.title': { tr: "Punch'ın Günlüğü", en: "Punch's Diary", de: "Punchs Tagebuch", fr: "Le Journal de Punch", ru: "Дневник Панча", ja: "パンチの日記", zh: "Punch的日记" },
  'report.subtitle': { tr: "Yapay zeka tarafından her gün internetten derlenen en güncel haberler ve gelişmeler.", en: "The latest news and updates compiled daily from the internet by AI.", de: "Die neuesten Nachrichten und Updates, täglich von KI aus dem Internet zusammengestellt.", fr: "Les dernières nouvelles et mises à jour compilées quotidiennement sur Internet par l'IA.", ru: "Последние новости и обновления, ежедневно собираемые ИИ из интернета.", ja: "AIによって毎日インターネットから収集される最新ニュースとアップデート。", zh: "人工智能每天从互联网上收集的最新新闻和更新。" },
  'report.ai_powered': { tr: "Yapay Zeka Destekli Rapor", en: "AI Powered Report", de: "KI-gestützter Bericht", fr: "Rapport généré par l'IA", ru: "Отчет на базе ИИ", ja: "AI搭載レポート", zh: "AI生成报告" },
  'report.loading': { tr: "İnternette güncel haberler taranıyor...", en: "Scanning the internet for latest news...", de: "Das Internet wird nach den neuesten Nachrichten durchsucht...", fr: "Recherche des dernières nouvelles sur Internet...", ru: "Поиск последних новостей в интернете...", ja: "インターネットで最新ニュースをスキャンしています...", zh: "正在互联网上扫描最新新闻..." },
  'report.error': { tr: "Rapor oluşturulamadı.", en: "Report could not be generated.", de: "Bericht konnte nicht erstellt werden.", fr: "Le rapport n'a pas pu être généré.", ru: "Не удалось создать отчет.", ja: "レポートを生成できませんでした。", zh: "无法生成报告。" },
  'report.fetch_error': { tr: "Günlük rapor alınırken bir hata oluştu. Lütfen daha sonra tekrar deneyin.", en: "An error occurred while fetching the daily report. Please try again later.", de: "Beim Abrufen des Tagesberichts ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.", fr: "Une erreur s'est produite lors de la récupération du rapport quotidien. Veuillez réessayer plus tard.", ru: "Произошла ошибка при получении ежедневного отчета. Пожалуйста, повторите попытку позже.", ja: "日次レポートの取得中にエラーが発生しました。後でもう一度お試しください。", zh: "获取每日报告时发生错误。请稍后再试。" },
  'report.sources': { tr: "Kaynaklar:", en: "Sources:", de: "Quellen:", fr: "Sources:", ru: "Источники:", ja: "ソース:", zh: "来源:" },
  
  'status.title': { tr: "Punch'ın Güncel Durumu", en: "Punch's Current Status", de: "Punchs aktueller Status", fr: "Statut actuel de Punch", ru: "Текущий статус Панча", ja: "パンチの現在のステータス", zh: "Punch的当前状态" },
  'status.japan_time': { tr: "Japonya Saati", en: "Japan Time", de: "Japanische Zeit", fr: "Heure du Japon", ru: "Японское время", ja: "日本時間", zh: "日本时间" },
  'status.current_activity': { tr: "Şu Anki Durumu", en: "Current Activity", de: "Aktuelle Aktivität", fr: "Activité actuelle", ru: "Текущая активность", ja: "現在のアクティビティ", zh: "当前活动" },
  'status.sleeping': { tr: "Şu an uykuda 😴", en: "Sleeping right now 😴", de: "Schläft gerade 😴", fr: "Dort en ce moment 😴", ru: "Сейчас спит 😴", ja: "今は寝ています 😴", zh: "现在正在睡觉 😴" },
  'status.waking': { tr: "Yeni uyanıyor, güne başlıyor 🌅", en: "Waking up, starting the day 🌅", de: "Wacht auf, beginnt den Tag 🌅", fr: "Se réveille, commence la journée 🌅", ru: "Просыпается, начинает день 🌅", ja: "起きて、一日を始めます 🌅", zh: "醒来，开始新的一天 🌅" },
  'status.playing': { tr: "Oyun oynuyor ve sosyalleşiyor 🐒", en: "Playing and socializing 🐒", de: "Spielt und sozialisiert 🐒", fr: "Joue et socialise 🐒", ru: "Играет и общается 🐒", ja: "遊んで社交しています 🐒", zh: "玩耍和社交 🐒" },
  'status.resting': { tr: "Öğle uykusunda veya dinleniyor 💤", en: "Taking a nap or resting 💤", de: "Macht ein Nickerchen oder ruht sich aus 💤", fr: "Fait une sieste ou se repose 💤", ru: "Дремлет или отдыхает 💤", ja: "昼寝をしているか休んでいます 💤", zh: "正在午睡或休息 💤" },
  'status.active': { tr: "Aktif, etrafı keşfediyor 🌿", en: "Active, exploring around 🌿", de: "Aktiv, erkundet die Umgebung 🌿", fr: "Actif, explore les environs 🌿", ru: "Активен, исследует окрестности 🌿", ja: "アクティブで、周りを探索しています 🌿", zh: "活跃，正在四处探索 🌿" },

  'map.title': { tr: "Ichikawa City Zoo", en: "Ichikawa City Zoo", de: "Ichikawa City Zoo", fr: "Zoo de la ville d'Ichikawa", ru: "Зоопарк Итикава", ja: "市川市動植物園", zh: "市川市动物园" },
  'map.subtitle': { tr: "Punch ve diğer makakların yaşadığı hayvanat bahçesi.", en: "The zoo where Punch and other macaques live.", de: "Der Zoo, in dem Punch und andere Makaken leben.", fr: "Le zoo où vivent Punch et d'autres macaques.", ru: "Зоопарк, где живут Панч и другие макаки.", ja: "パンチや他のマカクが住んでいる動物園。", zh: "Punch和其他猕猴生活的动物园。" },
  'map.directions': { tr: "Yol Tarifi Al", en: "Get Directions", de: "Wegbeschreibung erhalten", fr: "Obtenir des itinéraires", ru: "Проложить маршрут", ja: "ルートを取得", zh: "获取路线" },

  'live.title': { tr: "Canlı Yayın", en: "Live Stream", de: "Live-Stream", fr: "En direct", ru: "Прямой эфир", ja: "ライブ配信", zh: "直播" },
  'live.subtitle': { tr: "Punch'ı canlı izleyin.", en: "Watch Punch live.", de: "Sehen Sie Punch live.", fr: "Regardez Punch en direct.", ru: "Смотрите Панча в прямом эфире.", ja: "パンチをライブで見る。", zh: "观看Punch直播。" },
  'live.error.title': { tr: "Canlı Yayın Şu An Kullanılamıyor", en: "Live Stream Currently Unavailable", de: "Live-Stream derzeit nicht verfügbar", fr: "Flux en direct actuellement indisponible", ru: "Прямой эфир в настоящее время недоступен", ja: "現在ライブ配信は利用できません", zh: "直播目前不可用" },
  'live.error.desc': { tr: "Hayvanat bahçesi yönetimi tarafından sağlanan resmi ve sürekli bir canlı yayın akışı bulunmamaktadır. Punch'ın mahremiyeti ve stresi göz önünde bulundurularak 7/24 kamera yayını yapılmamaktadır.", en: "There is no official continuous live stream provided by the zoo management. To protect Punch's privacy and minimize stress, 24/7 camera broadcasting is not available.", de: "Es gibt keinen offiziellen kontinuierlichen Live-Stream, der von der Zooverwaltung bereitgestellt wird. Um Punchs Privatsphäre zu schützen und Stress zu minimieren, ist keine 24/7-Kameraübertragung verfügbar.", fr: "Il n'y a pas de flux en direct continu officiel fourni par la direction du zoo. Pour protéger la vie privée de Punch et minimiser le stress, la diffusion par caméra 24h/24 et 7j/7 n'est pas disponible.", ru: "Официальной непрерывной прямой трансляции, предоставляемой руководством зоопарка, нет. Чтобы защитить частную жизнь Панча и минимизировать стресс, круглосуточная трансляция с камер недоступна.", ja: "動物園の管理によって提供される公式の継続的なライブストリームはありません。パンチのプライバシーを保護し、ストレスを最小限に抑えるため、24時間年中無休のカメラ放送は利用できません。", zh: "动物园管理部门没有提供官方的连续直播。为了保护Punch的隐私并尽量减少压力，不提供24/7全天候摄像头广播。" },
  'live.error.alternative': { tr: "Bunun yerine Günlük Rapor sekmesinden Punch'ın güncel fotoğraflarına ve haberlerine ulaşabilirsiniz.", en: "Instead, you can check the Daily Report tab for the latest photos and news about Punch.", de: "Stattdessen können Sie auf der Registerkarte Tagesbericht nach den neuesten Fotos und Nachrichten über Punch suchen.", fr: "À la place, vous pouvez consulter l'onglet Rapport quotidien pour les dernières photos et nouvelles concernant Punch.", ru: "Вместо этого вы можете проверить вкладку «Ежедневный отчет» на наличие последних фотографий и новостей о Панче.", ja: "代わりに、日次レポートタブでパンチに関する最新の写真やニュースを確認できます。", zh: "相反，您可以查看“每日报告”选项卡，了解有关Punch的最新照片和新闻。" },

  'footer.rights': { tr: 'Tüm hakları saklıdır.', en: 'All rights reserved.', de: 'Alle Rechte vorbehalten.', fr: 'Tous droits réservés.', ru: 'Все права защищены.', ja: '全著作権所有。', zh: '版权所有。' },
  'footer.dedication': { tr: "Ichikawa City Zoo'daki sevimli dostumuz Punch'a adanmıştır.", en: 'Dedicated to our lovely friend Punch at Ichikawa City Zoo.', de: 'Gewidmet unserem lieben Freund Punch im Ichikawa City Zoo.', fr: 'Dédié à notre charmant ami Punch au zoo de la ville d\'Ichikawa.', ru: 'Посвящается нашему милому другу Панчу в зоопарке Итикава.', ja: '市川市動植物園の愛らしい友達パンチに捧げます。', zh: '献给我们在市川市动物园的可爱朋友Punch。' },
  'footer.developer': { tr: "Bu site Ahmet Tolga Özcan tarafından geliştirilmiştir.", en: "This site was developed by Ahmet Tolga Özcan.", de: "Diese Seite wurde von Ahmet Tolga Özcan entwickelt.", fr: "Ce site a été développé par Ahmet Tolga Özcan.", ru: "Этот сайт был разработан Ахметом Толгой Озджаном.", ja: "このサイトはAhmet Tolga Özcanによって開発されました。", zh: "本网站由Ahmet Tolga Özcan开发。" },
  'footer.contact': { tr: "Öneri, geliştirme ve siteyi satın almak için iletişim: ", en: "For suggestions, development, and purchasing the site, contact: ", de: "Für Vorschläge, Entwicklung und den Kauf der Website kontaktieren Sie: ", fr: "Pour des suggestions, le développement et l'achat du site, contactez: ", ru: "Для предложений, разработки и покупки сайта обращайтесь: ", ja: "提案、開発、サイトの購入については、お問い合わせください: ", zh: "有关建议、开发和购买网站，请联系：" },

  'about.title': { tr: "Punch Hakkında", en: "About Punch", de: "Über Punch", fr: "À propos de Punch", ru: "О Панче", ja: "パンチについて", zh: "关于Punch" },
  'about.subtitle': { tr: "İnternetin sevgilisi haline gelen yalnız ama güçlü yavru makak Punch'ın hikayesi.", en: "The story of Punch, the lonely but strong baby macaque who became the internet's darling.", de: "Die Geschichte von Punch, dem einsamen, aber starken Makakenbaby, das zum Liebling des Internets wurde.", fr: "L'histoire de Punch, le bébé macaque solitaire mais fort qui est devenu le chouchou d'Internet.", ru: "История Панча, одинокого, но сильного детеныша макаки, который стал любимцем интернета.", ja: "インターネットの寵児となった孤独で強いマカクの赤ちゃん、パンチの物語。", zh: "Punch的故事，这只孤独但坚强的猕猴宝宝成为了互联网的宠儿。" },
  'about.id_card': { tr: "Kimlik Kartı", en: "ID Card", de: "Ausweis", fr: "Carte d'identité", ru: "Удостоверение личности", ja: "IDカード", zh: "身份证" },
  'about.name': { tr: "İsim", en: "Name", de: "Name", fr: "Nom", ru: "Имя", ja: "名前", zh: "名字" },
  'about.species': { tr: "Tür", en: "Species", de: "Art", fr: "Espèce", ru: "Вид", ja: "種", zh: "物种" },
  'about.species_val': { tr: "Japon Makakı", en: "Japanese Macaque", de: "Japan-Makak", fr: "Macaque japonais", ru: "Японская макака", ja: "ニホンザル", zh: "日本猕猴" },
  'about.birth': { tr: "Doğum Tarihi", en: "Birth Date", de: "Geburtsdatum", fr: "Date de naissance", ru: "Дата рождения", ja: "生年月日", zh: "出生日期" },
  'about.birth_val': { tr: "25 Temmuz 2025", en: "July 25, 2025", de: "25. Juli 2025", fr: "25 juillet 2025", ru: "25 июля 2025 г.", ja: "2025年7月25日", zh: "2025年7月25日" },
  'about.gender': { tr: "Cinsiyet", en: "Gender", de: "Geschlecht", fr: "Sexe", ru: "Пол", ja: "性別", zh: "性别" },
  'about.gender_val': { tr: "Erkek", en: "Male", de: "Männlich", fr: "Mâle", ru: "Самец", ja: "オス", zh: "雄性" },
  'about.location': { tr: "Konum", en: "Location", de: "Standort", fr: "Emplacement", ru: "Расположение", ja: "場所", zh: "位置" },
  'about.age': { tr: "Yaş", en: "Age", de: "Alter", fr: "Âge", ru: "Возраст", ja: "年齢", zh: "年龄" },
  'about.weight': { tr: "Tahmini Ağırlık", en: "Est. Weight", de: "Geschätztes Gewicht", fr: "Poids estimé", ru: "Примерный вес", ja: "推定体重", zh: "估计重量" },
  'about.height': { tr: "Tahmini Boy", en: "Est. Height", de: "Geschätzte Größe", fr: "Taille estimée", ru: "Примерный рост", ja: "推定身長", zh: "估计高度" },
  'about.months': { tr: "aylık", en: "months old", de: "Monate alt", fr: "mois", ru: "месяцев", ja: "ヶ月", zh: "个月大" },
  'about.viral_title': { tr: "Neden Viral Oldu?", en: "Why Did He Go Viral?", de: "Warum wurde er viral?", fr: "Pourquoi est-il devenu viral ?", ru: "Почему он стал вирусным?", ja: "なぜ彼はバイラルになったのですか？", zh: "他为什么会走红？" },
  'about.viral_desc': { tr: "Annesi tarafından reddedilen Punch'ın, yalnızlığını gidermek için bakıcıları tarafından verilen bir IKEA orangutan peluşuna sarıldığı görüntüler internette büyük yankı uyandırdı.", en: "Rejected by his mother, Punch's images hugging an IKEA orangutan plush given by his caretakers to ease his loneliness made a huge impact on the internet.", de: "Von seiner Mutter abgelehnt, machten Punchs Bilder, die ein IKEA-Orang-Utan-Plüschtier umarmen, das ihm seine Betreuer gaben, um seine Einsamkeit zu lindern, einen großen Eindruck im Internet.", fr: "Rejeté par sa mère, les images de Punch étreignant une peluche orang-outan IKEA donnée par ses gardiens pour apaiser sa solitude ont eu un impact énorme sur Internet.", ru: "Отвергнутый матерью, изображения Панча, обнимающего плюшевого орангутанга IKEA, подаренного ему смотрителями, чтобы облегчить его одиночество, оказали огромное влияние на интернет.", ja: "母親に拒絶されたパンチが、孤独を和らげるために飼育員から与えられたIKEAのオランウータンのぬいぐるみを抱きしめている画像は、インターネットに大きな影響を与えました。", zh: "被母亲拒绝后，Punch拥抱看护人给他的宜家猩猩毛绒玩具以缓解孤独的画面在互联网上产生了巨大的影响。" },
  'about.early_title': { tr: "İlk Yılları ve Travması", en: "Early Years and Trauma", de: "Frühe Jahre und Trauma", fr: "Premières années et traumatisme", ru: "Ранние годы и травма", ja: "初期とトラウマ", zh: "早年与创伤" },
  'about.early_p1': { tr: "Punch, doğumundan kısa bir süre sonra annesi tarafından terk edildi. Bu durum genellikle deneyimsiz annelik, stresli doğum koşulları veya çevresel baskı gibi faktörlerle ilişkilendirilir.", en: "Punch was abandoned by his mother shortly after birth. This is often associated with factors such as inexperienced motherhood, stressful birth conditions, or environmental pressure.", de: "Punch wurde kurz nach der Geburt von seiner Mutter verlassen. Dies wird häufig mit Faktoren wie unerfahrener Mutterschaft, stressigen Geburtsbedingungen oder Umweltdruck in Verbindung gebracht.", fr: "Punch a été abandonné par sa mère peu après sa naissance. Cela est souvent associé à des facteurs tels qu'une maternité inexpérimentée, des conditions de naissance stressantes ou une pression environnementale.", ru: "Панч был брошен матерью вскоре после рождения. Это часто связано с такими факторами, как неопытное материнство, стрессовые условия родов или давление окружающей среды.", ja: "パンチは生後間もなく母親に見捨てられました。これは、経験の浅い母親、ストレスの多い出産条件、環境圧力などの要因に関連していることがよくあります。", zh: "Punch出生后不久就被母亲遗弃。这通常与缺乏经验的母亲、压力大的出生条件或环境压力等因素有关。" },
  'about.early_p2': { tr: "Primatologlara göre anne-yavru bağı, makaklarda fiziksel güç ve psikolojik güven için hayati önem taşır. Bu bağın olmaması, Punch'ta kaygı ve sosyal zorluk riskini artırdı. Bakımını üstlenen zookeperlar (hayvan bakıcıları), onu biberonla besleyerek büyüttü.", en: "According to primatologists, the mother-infant bond is vital for physical strength and psychological security in macaques. The absence of this bond increased the risk of anxiety and social difficulties in Punch. Zookeepers took over his care and raised him by bottle-feeding.", de: "Laut Primatologen ist die Mutter-Kind-Bindung für die körperliche Stärke und psychologische Sicherheit bei Makaken von entscheidender Bedeutung. Das Fehlen dieser Bindung erhöhte das Risiko von Angstzuständen und sozialen Schwierigkeiten bei Punch. Tierpfleger übernahmen seine Pflege und zogen ihn mit der Flasche auf.", fr: "Selon les primatologues, le lien mère-enfant est vital pour la force physique et la sécurité psychologique chez les macaques. L'absence de ce lien a augmenté le risque d'anxiété et de difficultés sociales chez Punch. Les gardiens de zoo ont pris en charge ses soins et l'ont élevé au biberon.", ru: "По мнению приматологов, связь матери и детеныша жизненно важна для физической силы и психологической безопасности макак. Отсутствие этой связи увеличивало риск беспокойства и социальных трудностей у Панча. Смотрители зоопарка взяли на себя заботу о нем и вырастили его, кормя из бутылочки.", ja: "霊長類学者によると、母子の絆はマカクの体力と心理的安全性にとって不可欠です。この絆の欠如は、パンチの不安や社会的困難のリスクを高めました。飼育員が彼の世話を引き継ぎ、哺乳瓶で育てました。", zh: "根据灵长类动物学家的说法，母婴纽带对猕猴的体力和心理安全至关重要。这种纽带的缺失增加了Punch焦虑和社交困难的风险。动物园管理员接管了他的照顾，并通过奶瓶喂养抚养他。" },
  'about.social_title': { tr: "Sosyal Zorluklar", en: "Social Difficulties", de: "Soziale Schwierigkeiten", fr: "Difficultés sociales", ru: "Социальные трудности", ja: "社会的困難", zh: "社交困难" },
  'about.social_p1': { tr: "Yaklaşık 60 makaktan oluşan \"Monkey Mountain\" grubuna katıldığında Punch, diğer makaklarla bağ kurmakta zorlandı. Zaman zaman dışlandı ve sosyal hiyerarşide baskı gördü.", en: "When he joined the \"Monkey Mountain\" group of about 60 macaques, Punch struggled to bond with other macaques. He was occasionally excluded and faced pressure in the social hierarchy.", de: "Als er sich der „Monkey Mountain“-Gruppe von etwa 60 Makaken anschloss, hatte Punch Mühe, sich mit anderen Makaken zu verbinden. Er wurde gelegentlich ausgeschlossen und sah sich dem Druck in der sozialen Hierarchie ausgesetzt.", fr: "Lorsqu'il a rejoint le groupe « Monkey Mountain » d'environ 60 macaques, Punch a eu du mal à créer des liens avec d'autres macaques. Il a parfois été exclu et a subi des pressions dans la hiérarchie sociale.", ru: "Когда он присоединился к группе «Обезьянья гора», состоящей примерно из 60 макак, Панч изо всех сил пытался сблизиться с другими макаками. Иногда его исключали, и он сталкивался с давлением в социальной иерархии.", ja: "約60匹のマカクの「モンキーマウンテン」グループに加わったとき、パンチは他のマカクと絆を結ぶのに苦労しました。彼は時々排除され、社会的階層で圧力に直面しました。", zh: "当他加入由大约60只猕猴组成的“猴山”群体时，Punch很难与其他猕猴建立联系。他偶尔会被排斥，并在社会等级中面临压力。" },
  'about.social_p2': { tr: "Ancak uzmanlar, bunun bir \"zorbalık\"tan ziyade normal makak sosyal düzeni olduğunu belirtiyor. Anne reddedilen makak yavrularında sosyal uyum gecikmesi, kaygı davranışları ve izolasyon eğilimi sıkça görülür.", en: "However, experts note that this is normal macaque social order rather than \"bullying\". Delayed social adaptation, anxiety behaviors, and a tendency towards isolation are common in mother-rejected macaque infants.", de: "Experten weisen jedoch darauf hin, dass dies eher eine normale soziale Ordnung der Makaken als „Mobbing“ ist. Verzögerte soziale Anpassung, Angstverhalten und eine Tendenz zur Isolation sind bei von der Mutter abgelehnten Makakenbabys häufig.", fr: "Cependant, les experts notent qu'il s'agit d'un ordre social normal des macaques plutôt que d'une « intimidation ». Un retard d'adaptation sociale, des comportements anxieux et une tendance à l'isolement sont fréquents chez les bébés macaques rejetés par leur mère.", ru: "Однако эксперты отмечают, что это нормальный социальный порядок макак, а не «издевательства». Задержка социальной адаптации, тревожное поведение и склонность к изоляции часто встречаются у детенышей макак, отвергнутых матерью.", ja: "しかし、専門家は、これは「いじめ」ではなく、通常のマカクの社会秩序であると指摘しています。母親に拒絶されたマカクの乳児には、社会的適応の遅れ、不安行動、孤立する傾向がよく見られます。", zh: "然而，专家指出，这是正常的猕猴社会秩序，而不是“欺凌”。在被母亲拒绝的猕猴婴儿中，社交适应延迟、焦虑行为和孤立倾向很常见。" },
  'about.plush_title': { tr: "Peluş Oyuncak \"Ora-mama\"", en: "Plush Toy \"Ora-mama\"", de: "Plüschtier „Ora-mama“", fr: "Jouet en peluche « Ora-mama »", ru: "Плюшевая игрушка «Ора-мама»", ja: "ぬいぐるみ「オラママ」", zh: "毛绒玩具“Ora-mama”" },
  'about.plush_p1': { tr: "Bakıcılar, anne yokluğunu psikolojik olarak telafi etmek ve tutunma refleksini desteklemek amacıyla Punch'a bir IKEA orangutan peluşu verdi. Punch, bu oyuncağı adeta bir \"vekil anne\" (surrogate mother) gibi benimsedi.", en: "Caretakers gave Punch an IKEA orangutan plush to psychologically compensate for the absence of his mother and support his clinging reflex. Punch adopted this toy almost like a \"surrogate mother\".", de: "Die Betreuer gaben Punch ein IKEA-Orang-Utan-Plüschtier, um die Abwesenheit seiner Mutter psychologisch zu kompensieren und seinen Klammerreflex zu unterstützen. Punch adoptierte dieses Spielzeug fast wie eine „Ersatzmutter“.", fr: "Les gardiens ont donné à Punch une peluche orang-outan IKEA pour compenser psychologiquement l'absence de sa mère et soutenir son réflexe d'accrochage. Punch a adopté ce jouet presque comme une « mère porteuse ».", ru: "Смотрители подарили Панчу плюшевого орангутанга IKEA, чтобы психологически компенсировать отсутствие матери и поддержать его рефлекс цепляния. Панч принял эту игрушку почти как «суррогатную мать».", ja: "飼育員は、母親の不在を心理的に補い、しがみつく反射をサポートするために、パンチにIKEAのオランウータンのぬいぐるみを与えました。パンチは、このおもちゃを「代理母」のように採用しました。", zh: "看护人给Punch一个宜家猩猩毛绒玩具，以在心理上弥补他母亲的缺席并支持他的攀附反射。Punch几乎把这个玩具当成了“代孕母亲”。" },
  'about.plush_p2': { tr: "İnternette \"Ora-mama\" olarak anılmaya başlayan bu oyuncak, Punch'ın stresini azaltan bir bağlanma ikamesi (attachment substitution) işlevi gördü. Bu görüntüler Şubat 2026'da viral olunca, IKEA peluşunun satışları %200 arttı ve oyuncak birçok ülkede tükendi.", en: "This toy, which started to be called \"Ora-mama\" on the internet, served as an attachment substitution that reduced Punch's stress. When these images went viral in February 2026, sales of the IKEA plush increased by 200% and the toy sold out in many countries.", de: "Dieses Spielzeug, das im Internet als „Ora-mama“ bezeichnet wurde, diente als Bindungsersatz, der Punchs Stress reduzierte. Als diese Bilder im Februar 2026 viral wurden, stiegen die Verkäufe des IKEA-Plüschtiers um 200 % und das Spielzeug war in vielen Ländern ausverkauft.", fr: "Ce jouet, qui a commencé à être appelé « Ora-mama » sur Internet, a servi de substitut d'attachement qui a réduit le stress de Punch. Lorsque ces images sont devenues virales en février 2026, les ventes de la peluche IKEA ont augmenté de 200 % et le jouet s'est vendu dans de nombreux pays.", ru: "Эта игрушка, которую в интернете стали называть «Ора-мама», послужила заменой привязанности, которая снизила стресс Панча. Когда эти изображения стали вирусными в феврале 2026 года, продажи плюшевых игрушек IKEA выросли на 200%, и игрушка была распродана во многих странах.", ja: "インターネットで「オラママ」と呼ばれるようになったこのおもちゃは、パンチのストレスを軽減する愛着の代替品として機能しました。これらの画像が2026年2月にバイラルになったとき、IKEAのぬいぐるみの売り上げは200％増加し、おもちゃは多くの国で売り切れました。", zh: "这个在互联网上被称为“Ora-mama”的玩具，作为一种依恋替代品，减轻了Punch的压力。当这些图像在2026年2月走红时，宜家毛绒玩具的销量增长了200%，并且在许多国家售罄。" },
  'about.current_title': { tr: "Güncel Durumu ve Gelecek", en: "Current Status and Future", de: "Aktueller Status und Zukunft", fr: "Statut actuel et avenir", ru: "Текущий статус и будущее", ja: "現在の状況と将来", zh: "现状与未来" },
  'about.current_p1': { tr: "Son gözlemler oldukça umut verici. Punch fiziksel olarak sağlıklı, diğer makaklarla etkileşimi başladı ve \"grooming\" (tımarlama) davranışı gösteriyor. Bazı bireylerle oyun oynayarak sosyal öğrenmesini geliştiriyor.", en: "Recent observations are quite promising. Punch is physically healthy, has started interacting with other macaques, and shows \"grooming\" behavior. He is developing his social learning by playing with some individuals.", de: "Jüngste Beobachtungen sind sehr vielversprechend. Punch ist körperlich gesund, hat begonnen, mit anderen Makaken zu interagieren, und zeigt „Grooming“-Verhalten. Er entwickelt sein soziales Lernen, indem er mit einigen Individuen spielt.", fr: "Les observations récentes sont très prometteuses. Punch est physiquement en bonne santé, a commencé à interagir avec d'autres macaques et montre un comportement de « toilettage ». Il développe son apprentissage social en jouant avec certains individus.", ru: "Последние наблюдения весьма многообещающие. Панч физически здоров, начал взаимодействовать с другими макаками и демонстрирует поведение «ухода». Он развивает свое социальное обучение, играя с некоторыми особями.", ja: "最近の観察は非常に有望です。パンチは肉体的に健康で、他のマカクと交流し始め、「グルーミング」行動を示しています。彼は一部の個人と遊ぶことで社会的学習を発展させています。", zh: "最近的观察非常有希望。Punch身体健康，已开始与其他猕猴互动，并表现出“梳理”行为。他正在通过与一些个体玩耍来发展他的社会学习。" },
  'about.current_p2': { tr: "Uzmanlar, kısa vadede sosyal entegrasyonunun artmasını ve oyuncağa bağımlılığının azalmasını bekliyor. Ancak uzun vadeli sosyal statüsü ve grup içi kabulü yakından izlenmeye devam ediyor.", en: "Experts expect his social integration to increase and his dependence on the toy to decrease in the short term. However, his long-term social status and in-group acceptance continue to be closely monitored.", de: "Experten erwarten, dass seine soziale Integration zunimmt und seine Abhängigkeit vom Spielzeug kurzfristig abnimmt. Sein langfristiger sozialer Status und seine Akzeptanz in der Gruppe werden jedoch weiterhin genau überwacht.", fr: "Les experts s'attendent à ce que son intégration sociale augmente et que sa dépendance au jouet diminue à court terme. Cependant, son statut social à long terme et son acceptation au sein du groupe continuent d'être étroitement surveillés.", ru: "Эксперты ожидают, что его социальная интеграция увеличится, а его зависимость от игрушки уменьшится в краткосрочной перспективе. Однако его долгосрочный социальный статус и признание в группе продолжают внимательно отслеживаться.", ja: "専門家は、短期的には彼の社会的統合が高まり、おもちゃへの依存度が低下すると予想しています。しかし、彼の長期的な社会的地位とグループ内での受け入れは引き続き綿密に監視されています。", zh: "专家预计，在短期内，他的社会融合度将提高，对玩具的依赖度将降低。然而，他的长期社会地位和群体内接受度将继续受到密切监控。" },

  'about.facts_title': { tr: "Japon Makakları Hakkında İlginç Bilgiler", en: "Interesting Facts About Japanese Macaques", de: "Interessante Fakten über Japan-Makaken", fr: "Faits intéressants sur les macaques japonais", ru: "Интересные факты о японских макаках", ja: "ニホンザルに関する興味深い事実", zh: "关于日本猕猴的有趣事实" },
  'about.fact1_title': { tr: "Kar Maymunları", en: "Snow Monkeys", de: "Schneeaffen", fr: "Singes des neiges", ru: "Снежные обезьяны", ja: "スノーモンキー", zh: "雪猴" },
  'about.fact1_desc': { tr: "Japon makakları, dünyada insandan sonra en kuzeyde ve en soğuk iklimde yaşayan primatlardır. Kalın kürkleri sayesinde -15°C'ye kadar dayanabilirler.", en: "Japanese macaques are the northernmost-living non-human primates in the world. Thanks to their thick fur, they can survive temperatures down to -15°C.", de: "Japan-Makaken sind die am weitesten nördlich lebenden nicht-menschlichen Primaten der Welt. Dank ihres dicken Fells können sie Temperaturen bis zu -15 °C überleben.", fr: "Les macaques japonais sont les primates non humains vivant le plus au nord du monde. Grâce à leur fourrure épaisse, ils peuvent survivre à des températures allant jusqu'à -15°C.", ru: "Японские макаки — самые северные нечеловекообразные приматы в мире. Благодаря густому меху они могут выживать при температуре до -15°C.", ja: "ニホンザルは、世界で最も北に生息する人間以外の霊長類です。厚い毛皮のおかげで、-15°Cまでの温度で生き残ることができます。", zh: "日本猕猴是世界上生活在最北端的非人类灵长类动物。由于它们厚厚的皮毛，它们可以在低至-15°C的温度下生存。" },
  'about.fact2_title': { tr: "Kaplıca Keyfi", en: "Hot Spring Lovers", de: "Liebhaber heißer Quellen", fr: "Amateurs de sources chaudes", ru: "Любители горячих источников", ja: "温泉好き", zh: "温泉爱好者" },
  'about.fact2_desc': { tr: "Özellikle Jigokudani bölgesindeki makaklar, kışın ısınmak için doğal volkanik kaplıcalara (onsen) girmeleriyle ünlüdür. Bu davranışı sonradan öğrenmiş ve nesilden nesile aktarmışlardır.", en: "Macaques, especially in the Jigokudani area, are famous for bathing in natural volcanic hot springs (onsen) to stay warm in winter. They learned this behavior and passed it down through generations.", de: "Makaken, insbesondere im Gebiet Jigokudani, sind dafür bekannt, in natürlichen vulkanischen heißen Quellen (Onsen) zu baden, um sich im Winter warm zu halten. Sie lernten dieses Verhalten und gaben es über Generationen weiter.", fr: "Les macaques, en particulier dans la région de Jigokudani, sont célèbres pour se baigner dans des sources chaudes volcaniques naturelles (onsen) pour se réchauffer en hiver. Ils ont appris ce comportement et l'ont transmis de génération en génération.", ru: "Макаки, особенно в районе Дзигокудани, известны тем, что купаются в природных вулканических горячих источниках (онсэнах), чтобы согреться зимой. Они научились этому поведению и передавали его из поколения в поколение.", ja: "特に地獄谷地域にいるマカクは、冬に暖かく保つために天然の火山温泉（温泉）に入浴することで有名です。彼らはこの行動を学び、何世代にもわたって受け継いできました。", zh: "猕猴，特别是在地狱谷地区，以在天然火山温泉（onsen）中沐浴以在冬天保暖而闻名。他们学会了这种行为并代代相传。" },
  'about.fact3_title': { tr: "Kültürel Öğrenme", en: "Cultural Learning", de: "Kulturelles Lernen", fr: "Apprentissage culturel", ru: "Культурное обучение", ja: "文化的学習", zh: "文化学习" },
  'about.fact3_desc': { tr: "Japon makakları çok zekidir. Tatlı patatesleri yemeden önce deniz suyunda yıkayarak hem temizlemeyi hem de tuzla tatlandırmayı keşfetmişlerdir.", en: "Japanese macaques are highly intelligent. They discovered how to wash sweet potatoes in seawater before eating them, both to clean them and to season them with salt.", de: "Japan-Makaken sind hochintelligent. Sie entdeckten, wie man Süßkartoffeln vor dem Essen in Meerwasser wäscht, um sie sowohl zu reinigen als auch mit Salz zu würzen.", fr: "Les macaques japonais sont très intelligents. Ils ont découvert comment laver les patates douces dans l'eau de mer avant de les manger, à la fois pour les nettoyer et les assaisonner de sel.", ru: "Японские макаки очень умны. Они открыли, как мыть сладкий картофель в морской воде перед едой, чтобы очистить его и приправить солью.", ja: "ニホンザルは非常に知能が高いです。彼らは、食べる前にサツマイモを海水で洗う方法を発見しました。これは、サツマイモをきれいにし、塩で味付けするためです。", zh: "日本猕猴非常聪明。他们发现了在吃红薯之前如何在海水中清洗红薯，既可以清洁红薯，又可以用盐调味。" },
  'about.fact4_title': { tr: "Anaerkil Toplum", en: "Matriarchal Society", de: "Matriarchalische Gesellschaft", fr: "Société matriarcale", ru: "Матриархальное общество", ja: "母系社会", zh: "母系社会" },
  'about.fact4_desc': { tr: "Makak grupları genellikle dişiler etrafında şekillenir. Dişiler doğdukları grupta kalırken, erkekler ergenliğe ulaştıklarında başka gruplara katılırlar.", en: "Macaque groups are generally structured around females. Females stay in their natal group, while males leave to join other groups when they reach puberty.", de: "Makakengruppen sind im Allgemeinen um Weibchen strukturiert. Weibchen bleiben in ihrer Geburtsgruppe, während Männchen diese verlassen, um sich anderen Gruppen anzuschließen, wenn sie die Pubertät erreichen.", fr: "Les groupes de macaques sont généralement structurés autour de femelles. Les femelles restent dans leur groupe natal, tandis que les mâles partent pour rejoindre d'autres groupes lorsqu'ils atteignent la puberté.", ru: "Группы макак обычно структурированы вокруг самок. Самки остаются в своей родной группе, в то время как самцы уходят, чтобы присоединиться к другим группам, когда они достигают половой зрелости.", ja: "マカクのグループは一般的にメスを中心に構成されています。メスは生まれたグループにとどまりますが、オスは思春期に達すると他のグループに加わるために去ります。", zh: "猕猴群体通常围绕雌性构成。雌性留在她们出生的群体中，而雄性在达到青春期时会离开加入其他群体。" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('tr');

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const { latitude, longitude } = position.coords;
          // Turkey rough bounding box: lat 36-42, lon 26-45
          if (latitude >= 36 && latitude <= 42 && longitude >= 26 && longitude <= 45) {
            setLanguage('tr');
          } else {
            setLanguage('en');
          }
        },
        (error) => {
          console.log("Geolocation denied or error, defaulting to TR", error);
          setLanguage('tr');
        },
        { timeout: 5000 }
      );
    }
  }, []);

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
